### ISSUE TITLE
web

### ISSUE THREAD

**Issue by MMAKENPO** [Ekhart86/itunes-searcher#1]
hello my friend!!!please the web for your itunes project?

**Comment by Ekhart86** [comment]
Hello, this is a simple training project, used a free api, I do not plan to develop it

**Comment by MMAKENPO** [comment]
oooooooooooooo please my good friend!!!!can you develop it?it will be great!!!my friend I love so much spanish music...and I want find all the albums!!!I am begging you mannnnnnnnnnnn

**Comment by MMAKENPO** [comment]
oooooooooooooo please my good friend!!!!can you develop it?it will be great!!!my friend I love so much spanish music...and I want find all the albums!!!I am begging you mannnnnnnnnnnn

**Comment by Ekhart86** [comment]
Sorry Friend, but I don't have time for this... There are a lot of similar apps in the Play Market that would help you. And I think there's a web, too, look, I'm sure you'll find
